"use client";

import { useState, useEffect } from "react";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Copy, Download, Minimize2 } from "lucide-react";
import { toast } from "sonner";

function optimizeSvg(svg: string): string {
  return svg
    // Remove XML declaration
    .replace(/<\?xml[^>]*\?>/gi, "")
    // Remove comments
    .replace(/<!--[\s\S]*?-->/g, "")
    // Remove metadata, title, desc
    .replace(/<metadata[\s\S]*?<\/metadata>/gi, "")
    .replace(/<title[\s\S]*?<\/title>/gi, "")
    .replace(/<desc[\s\S]*?<\/desc>/gi, "")
    // Remove empty groups
    .replace(/<g[^>]*>\s*<\/g>/gi, "")
    // Remove unnecessary whitespace in attributes
    .replace(/\s{2,}/g, " ")
    // Remove whitespace between tags
    .replace(/>\s+</g, "><")
    // Remove unnecessary precision in numbers (4 decimal places → 2)
    .replace(/(\d+\.\d{3,})/g, m => parseFloat(m).toFixed(2))
    // Remove default attribute values
    .replace(/\s+fill="none"/g, "")
    .replace(/\s+stroke-width="1"/g, "")
    .replace(/\s+stroke="none"/g, "")
    // Remove style attributes that are empty
    .replace(/\s+style=""/g, "")
    // Trim
    .trim();
}

const SAMPLE_SVG = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Adobe Illustrator -->
<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100">
  <title>Sample Icon</title>
  <desc>A sample SVG icon for testing</desc>
  <metadata>Some metadata here</metadata>
  <g id="layer1" fill="none">
    <circle cx="50.0000" cy="50.0000" r="40.0000" stroke="#333333" stroke-width="2.0000" fill="#ff6600"/>
    <path d="M 30.000000 50 L 70.000000 50" stroke="#ffffff" stroke-width="4.0000"/>
  </g>
</svg>`;

export function SvgOptimizerTool() {
  const [input, setInput] = useState(SAMPLE_SVG);
  const [output, setOutput] = useState("");
  const [stats, setStats] = useState<{ original: number; optimized: number; savings: number } | null>(null);

  const optimize = () => {
    const opt = optimizeSvg(input);
    setOutput(opt);
    setStats({ original: input.length, optimized: opt.length, savings: Math.round((1 - opt.length / input.length) * 100) });
  };

  const copy = () => { navigator.clipboard.writeText(output); toast.success("Copied!"); };

  const download = () => {
    const blob = new Blob([output], { type: "image/svg+xml" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href = url; a.download = "optimized.svg"; a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="rounded-2xl border border-border bg-card overflow-hidden">
      <div className="flex items-center gap-2 px-4 py-3 border-b border-border bg-muted/30">
        <Minimize2 className="w-4 h-4 text-primary" />
        <span className="text-sm font-medium">SVG Optimizer</span>
      </div>
      <div className="p-5 space-y-4">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          <div>
            <label className="text-xs text-muted-foreground mb-1 block">Input SVG</label>
            <Textarea value={input} onChange={e=>setInput(e.target.value)} className="min-h-[280px] resize-none text-xs font-mono" />
            <p className="text-xs text-muted-foreground mt-1">{input.length} bytes</p>
          </div>
          <div>
            <div className="flex items-center justify-between mb-1">
              <label className="text-xs text-muted-foreground">Optimized SVG</label>
              {output && (
                <div className="flex gap-1">
                  <Button size="sm" variant="ghost" onClick={copy} className="h-6 text-xs gap-1"><Copy className="w-3 h-3" />Copy</Button>
                  <Button size="sm" variant="ghost" onClick={download} className="h-6 text-xs gap-1"><Download className="w-3 h-3" />Save</Button>
                </div>
              )}
            </div>
            <Textarea readOnly value={output} className="min-h-[280px] resize-none text-xs font-mono bg-muted/10" placeholder="Click Optimize to see results…" />
            {stats && <p className="text-xs text-muted-foreground mt-1">{stats.optimized} bytes</p>}
          </div>
        </div>

        <Button onClick={optimize} disabled={!input.trim()} className="w-full gap-2">
          <Minimize2 className="w-4 h-4" />Optimize SVG
        </Button>

        {stats && (
          <div className="flex items-center gap-4 p-3 rounded-xl border border-emerald-500/20 bg-emerald-500/5">
            <div className="text-center">
              <p className="text-xs text-muted-foreground">Original</p>
              <p className="text-sm font-mono font-medium">{stats.original} B</p>
            </div>
            <div className="text-center flex-1">
              <p className="text-xs text-muted-foreground">Saved</p>
              <p className="text-xl font-mono font-bold text-emerald-500">{stats.savings}%</p>
            </div>
            <div className="text-center">
              <p className="text-xs text-muted-foreground">Optimized</p>
              <p className="text-sm font-mono font-medium">{stats.optimized} B</p>
            </div>
          </div>
        )}

        {output && (
          <div>
            <p className="text-xs text-muted-foreground mb-2">Preview</p>
            <div className="flex items-center justify-center p-8 border border-border rounded-xl bg-muted/10 min-h-[100px]">
              <div dangerouslySetInnerHTML={{ __html: output }} className="max-w-full max-h-32" />
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
